/** Application route paths — single source of truth */
export const ROUTES = {
  home: '/',
  about: '/about',
  ourStory: '/our-story',
  ingredients: '/ingredients',
  ingredientDetail: '/ingredients/:slug',
  women: '/women',
  men: '/men',
  concerns: '/concerns',
  concernDetail: '/concerns/:slug',
  giftSets: '/gift-sets',
  skinQuiz: '/skin-quiz',
  shop: '/shop',
  skinCare: '/shop/skin-care',
  bodyCare: '/shop/body-care',
  hairCare: '/shop/hair-care',
  essentialOils: '/shop/essential-oils',
  coldPressedOils: '/shop/cold-pressed-oils',
  combos: '/shop/combos',
  bestSellers: '/shop/best-sellers',
  newArrivals: '/shop/new-arrivals',
  product: '/product/:slug',
  search: '/search',
  cart: '/cart',
  checkout: '/checkout',
  payment: '/checkout/payment',
  orderSuccess: '/order/success',
  orderHistory: '/account/orders',
  account: '/account',
  profile: '/account/profile',
  addresses: '/account/addresses',
  wishlist: '/account/wishlist',
  blog: '/blog',
  article: '/blog/:slug',
  faq: '/faq',
  contact: '/contact',
  storeLocator: '/store-locator',
  privacy: '/privacy-policy',
  returns: '/return-policy',
  shipping: '/shipping-policy',
  terms: '/terms',
  login: '/auth/login',
  register: '/auth/register',
  forgotPassword: '/auth/forgot-password',
  notFound: '*',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
