export const ADMIN_API = {
  login: '/auth/login',
  logout: '/auth/logout',
  me: '/auth/me',
  changePassword: '/auth/change-password',
  dashboard: '/admin/dashboard',
  orders: '/admin/orders',
  order: (id: string) => `/admin/orders/${id}`,
  orderStatus: (id: string) => `/admin/orders/${id}`,
  users: '/admin/users',
  user: (id: string) => `/admin/users/${id}`,
  products: '/admin/products',
  product: (id: string) => `/admin/products/${id}`,
  categories: '/admin/categories',
  category: (slug: string) => `/admin/categories/${slug}`,
  coupons: '/admin/coupons',
  coupon: (id: string) => `/admin/coupons/${id}`,
  reviews: '/admin/reviews',
  review: (id: string) => `/admin/reviews/${id}`,
  inventory: '/admin/inventory',
  upload: '/upload',
  notifications: '/admin/notifications',
  settings: '/admin/settings',
  analytics: '/admin/analytics/dashboard',
  contactInquiries: '/contact/admin',
  contactInquiry: (id: string) => `/contact/admin/${id}`,
} as const
