export const ADMIN_API = {
  login: '/auth/login',
  me: '/auth/me',
  changePassword: '/auth/change-password',
  dashboard: '/admin/dashboard',
  orders: '/admin/orders',
  orderStatus: (id: string) => `/admin/orders/${id}`,
  users: '/admin/users',
  products: '/admin/products',
  product: (id: string) => `/admin/products/${id}`,
  categories: '/admin/categories',
  coupons: '/admin/coupons',
  reviews: '/admin/reviews',
  blogs: '/admin/blogs',
  inventory: '/admin/inventory',
  media: '/admin/media',
  notifications: '/admin/notifications',
  settings: '/admin/settings',
  analytics: '/admin/analytics/dashboard',
} as const
