export const ADMIN_ROUTES = {
  login: '/login',
  dashboard: '/',
  orders: '/orders',
  orderDetail: '/orders/:id',
  products: '/products',
  productCreate: '/products/new',
  productEdit: '/products/:id/edit',
  categories: '/categories',
  users: '/users',
  coupons: '/coupons',
  inventory: '/inventory',
  reviews: '/reviews',
  blogs: '/blogs',
  blogCreate: '/blogs/new',
  blogEdit: '/blogs/:id/edit',
  analytics: '/analytics',
  sales: '/sales',
  media: '/media',
  settings: '/settings',
  notifications: '/notifications',
} as const
